### ISSUE TITLE
fontello font urls broken

### ISSUE THREAD

**Issue by Munter** [survivejs/site#29]
These font url's in your main.css are invalid web url's:

```css
@font-face {
    font-family: 'fontello';
    src: url(/Users/juhovepsalainen/Projects/survivejs/site/.antwar/buildc52f9a4d454a7095eee4d7e954c3e12a.eot);
    src: url(/Users/juhovepsalainen/Projects/survivejs/site/.antwar/buildc52f9a4d454a7095eee4d7e954c3e12a.eot#iefix) format('embedded-opentype'), url(<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg">...</svg>#fontello) format('svg');
    font-weight: normal;
    font-style: normal;
}
```
